#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Create and upload coverage report

on:
  workflow_call:
    inputs:
      coveragereports:
        description: |
          A string containing all names of the .xcresult files that are downloaded from the artifacts of previous jobs.
          Multiple values are separated by a space character.
        required: false
        type: string
      coveragereport_lcov:
        description: |
          A string with the path to an lcov file that are downloaded from the artifacts of previous jobs.
        required: false
        type: string
    secrets:
      token:
        description: 'The CodeCov token used for private repositories'
        required: false

jobs:
  create-and-upload-coverage-report:
    name: Create and upload coverage report
    runs-on: macos-26
    steps:
      - name: Check coverage inputs
        run: |
          if [ -z "${{ inputs.coveragereports }}" ] && [ -z "${{ inputs.coveragereport_lcov }}" ]; then
            echo "Error: Either coveragereports or coveragereport_lcov must be provided"
            exit 1
          fi
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Check environment
        run: |
            xcodebuild -version
            swift --version
      - uses: actions/download-artifact@v4
      - name: Ensure lcov is installed
        if: ${{ inputs.coveragereport_lcov != '' }}
        run: |
          if ! command -v lcov &> /dev/null; then
            echo "Installing lcov..."
            brew install lcov
          fi
      - name: Merge coverage reports
        if: ${{ inputs.coveragereports != '' }}
        run: |
            FILES=( ${{ inputs.coveragereports }} )
            NUM_INPUTS=${#FILES[@]}
            if [ $NUM_INPUTS -gt 1 ]; then
              xcrun xcresulttool merge ${{ inputs.coveragereports }} --output-path CodeCoverage.xcresult
              rm -rf ${{ inputs.coveragereports }}
            else
              mv ${{ inputs.coveragereports }} CodeCoverage.xcresult
            fi
      - name: Convert xcresult to lcov
        if: ${{ inputs.coveragereports != '' }}
        shell: bash
        run: |
          set -e
          URL="https://github.com/StanfordBDHG/xccov2lcov/releases/latest/download/xccov2lcov-macos.tar.gz"
          curl -f -sL "${URL}" -o xccov2lcov.tar.gz
          tar -xzf xccov2lcov.tar.gz
          chmod +x xccov2lcov
          xcrun xccov view --report --json CodeCoverage.xcresult | ./xccov2lcov --trim-path=/Users/githubaction/runner/_work/ > info.lcov
      - name: Combine with lcov files
        if: ${{ inputs.coveragereport_lcov != '' && inputs.coveragereports != '' }}
        run: |
          if [ -n "${{ inputs.coveragereport_lcov }}" ]; then
            lcov -a info.lcov -a ${{ inputs.coveragereport_lcov }}/${{ inputs.coveragereport_lcov }} -o coverage_combined.lcov
            mv coverage_combined.lcov info.lcov
          fi
      - name: Prepare LCOV for upload
        if: ${{ inputs.coveragereport_lcov != '' && inputs.coveragereports == '' }}
        run: |
          mv ${{ inputs.coveragereport_lcov }}/${{ inputs.coveragereport_lcov }} info.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: info.lcov
          token: ${{ secrets.token }}